---

- name: Ensure IP added
  template:
    src: templates/floating-ip.yaml.j2
    dest: "/etc/netplan/{{ floating_ip_netplan_yml }}"
  notify: netplan apply

- name: Force netplan apply
  meta: flush_handlers

...